language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
branches:
 only:
 - master
 - dev

before_install:
 - pip install pytest-cov
install:
 - pip install -e .

script:
 - py.test --cov=./

after_success:
 - pip install codecov; codecov;
