language: python
dist: xenial
jobs:
 include:
 - python: 3.5
 - python: 3.6
    - pip install equilibrator_cache>=0.2.6 equilibrator_api
 - python: 3.7
    - pip install equilibrator_cache>=0.2.6 equilibrator_api

branches:
 only:
 - master
 - dev

install:
 - pip install .

script:
 -  coverage run -m py.test tests

after_success:
 - pip install codecov; codecov
