language: python
dist: xenial
jobs:
 include:
 - python: 3.5
  before_install:
    - pip install coverage
 - python: 3.6
   before_install:
    - pip install coverage
    - pip install equilibrator_cache>=0.2.6 equilibrator_api
 - python: 3.7
   before_install:
    - pip install coverage
    - pip install equilibrator_cache>=0.2.6 equilibrator_api

branches:
 only:
 - master
 - dev

install:
 - pip install .

script:
 - coverage run --source pytfa -m py.test
 - coverage report

after_success:
 - pip install codecov; codecov
