language: python
dist: xenial
jobs:
 include:
 - python: 3.5
   before_install:
    - pip install pytest-cov
 - python: 3.6
   before_install:
    - pip install pytest-cov
    - pip install equilibrator>=0.2.6
 - python: 3.7
   before_install:
    - pip install pytest-cov
    - pip install equilibrator>=0.2.6
branches:
 only:
 - master
 - dev

install:
 - pip install .

script:
 - py.test --cov=./

after_success:
 - pip install codecov; codecov;
